### ISSUE TITLE
Use --recursive when cloning theos

### ISSUE THREAD

**Issue by supermamon** [MattrAus/iOS-Tweak-Development-for-Windows#1]
Saves you a step gettIng headers. 
https://github.com/theos/theos/wiki/Installation

**Comment by sctigercat1** [comment]
In addition, it seems like [this step](https://github.com/MattrAus/iOS-Tweak-Development-for-Windows#installing-headers) would also be unnecessary if you used --recursive (as it already downloads the headers into vendor/include).
