### ISSUE TITLE
No directory .git?

### ISSUE THREAD

**Issue by Geczy** [MattrAus/iOS-Tweak-Development-for-Windows#2]
`$ mv $THEOS/temp/.git $THEOS/include/.git                                       mv: cannot move '/opt/theos/temp/.git' to '/opt/theos/include/.git': No such file or directory`

**Comment by MattrAus** [comment]
Have you done all previous steps?

**Comment by Geczy** [comment]
I have done them all

**Comment by MattrAus** [comment]
What's your `C:\cygwin64\opt\theos` folder look like?

**Comment by Geczy** [comment]
includes
sdks
toolchain

**Comment by Geczy** [comment]
![image](https://cloud.githubusercontent.com/assets/1036968/17641119/4a54c120-60e1-11e6-9820-cf75a9d34a67.png)

**Comment by MattrAus** [comment]
Try `git clone --recursive https://github.com/theos/theos.git $THEOS/`

**Comment by Geczy** [comment]
Ok I did that now I have more files but still the same error

$ mv $THEOS/temp/.git $THEOS/include/.git
mv: cannot stat '/opt/theos/temp/.git': No such file or directory



![image](https://cloud.githubusercontent.com/assets/1036968/17643556/25731f50-613b-11e6-9f33-9cf46f375660.png)

**Comment by Geczy** [comment]
Ok now it works, thank you
