### ISSUE TITLE
Issue with lynx

### ISSUE THREAD

**Issue by ghost** [MattrAus/iOS-Tweak-Development-for-Windows#5]
Trying to get set up on windows 8 here, whenever I input the following code from the beginning of your tutorial

" lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg  
install apt-cyg /bin "

I receive the error " -bash: lynx: command not found "

**Comment by MattrAus** [comment]
Did you install Lynx when installing Cygwin?
https://github.com/MattrAus/iOS-Tweak-Development-for-Windows#installing-initial-cygwin-package

**Comment by MattrAus** [comment]
Closed issue as the solutions seems to be solved.
